#!/bin/sh /etc/rc.common

START=91
STOP=91

USE_PROCD=1

start_service() {
	echo "inserting hw_nat.ko!" > /tmp/hwnat.log
	insmod /lib/modules/ralink/hw_nat.ko
	echo "create /dev/hwnat0"
	mknod /dev/hwnat0 c 220 0
}

stop_service() {
	echo "removing hw_nat.ko" >> /tmp.hwnat.log
	rmmod hw_nat.ko
}


